import api from '@/services/api';

export const adminAPI = {
  getSuperAdminDashboard: () => api.get('/admin/super-admin'),
  getCollegeDashboard: () => api.get('/admin/college'),
  getDepartmentDashboard: () => api.get('/admin/department'),
  getAnalyticsDashboard: () => api.get('/admin/analytics'),
  getFraudDetection: () => api.get('/admin/fraud-detection'),
  getCertificates: (params = {}) => api.get('/admin/certificates', { params }),
  verifyCertificate: (applicationId, payload) => api.put(`/admin/certificates/${applicationId}/verify`, payload),
  issueCertificate: (applicationId) => api.put(`/admin/certificates/${applicationId}/issue`),
  getInternshipStatistics: () => api.get('/admin/reports/internship-statistics'),
  generateReport: (payload = {}) => api.post('/admin/reports/generate', payload),
  getEvaluations: () => api.get('/evaluation/admin/all'),
  getSettingsOverview: () => api.get('/admin/settings'),
  getSecurityOverview: () => api.get('/admin/security-overview'),
  updateRolePermissions: (payload) => api.put('/admin/settings/permissions', payload),
  updateSystemConfig: (payload) => api.put('/admin/settings/config', payload),
  getUsers: (params = {}) => api.get('/admin/users', { params }),
  getStudents: (params = {}) => api.get('/admin/students', { params }),
  getCompanies: (params = {}) => api.get('/admin/companies', { params }),
  getCompanyProfile: (id) => api.get(`/admin/companies/${id}`),
  getDeanCandidates: () => api.get('/admin/college-deans'),
  getInternships: (params = {}) => api.get('/admin/internships', { params }),
  getApplications: (params = {}) => api.get('/admin/applications', { params }),
  exportUsers: (params = {}) => api.get('/admin/users/export', { params, responseType: 'blob' }),
  exportStudents: (params = {}) => api.get('/admin/students/export', { params, responseType: 'blob' }),
  exportCompanies: (params = {}) => api.get('/admin/companies/export', { params, responseType: 'blob' }),
  exportInternships: (params = {}) => api.get('/admin/internships/export', { params, responseType: 'blob' }),
  exportApplications: (params = {}) => api.get('/admin/applications/export', { params, responseType: 'blob' }),
  updateCompanyVerification: (id, payload) => api.put(`/admin/companies/${id}/verification`, payload),
  updateInternshipStatus: (id, payload) => api.put(`/admin/internships/${id}/status`, payload),
  updateApplicationStatus: (id, payload) => api.put(`/admin/applications/${id}/status`, payload),
  getAuditLogs: (params = {}) => api.get('/admin/audit-logs', { params }),
  exportAuditLogs: (params = {}) => api.get('/admin/audit-logs/export', { params, responseType: 'blob' }),
  getColleges: () => api.get('/admin/colleges'),
  exportColleges: () => api.get('/admin/colleges/export', { responseType: 'blob' }),
  createCollege: (payload) => api.post('/admin/colleges', payload),
  updateCollege: (id, payload) => api.put(`/admin/colleges/${id}`, payload),
  assignCollegeDean: (id, payload) => api.put(`/admin/colleges/${id}/dean`, payload),
  resetCollegeDeanPassword: (id) => api.post(`/admin/colleges/${id}/dean/reset-password`),
  deleteCollege: (id) => api.delete(`/admin/colleges/${id}`),
  getDepartments: () => api.get('/admin/departments'),
  getDepartmentHeadCandidates: () => api.get('/admin/department-heads'),
  createDepartment: (payload) => api.post('/admin/departments', payload),
  updateDepartment: (id, payload) => api.put(`/admin/departments/${id}`, payload),
  assignDepartmentHead: (id, payload) => api.put(`/admin/departments/${id}/head`, payload),
  getAdminNotifications: (params = {}) => api.get('/admin/notifications', { params }),
  sendAnnouncement: (payload) => api.post('/admin/notifications/announce', payload),
  getNotifications: (params = {}) => api.get('/notification', { params }),
  markNotificationRead: (id) => api.put(`/notification/read/${id}`),
  markAllNotificationsRead: () => api.put('/notification/read-all'),
  deleteNotification: (id) => api.delete(`/notification/${id}`)
};
